const GeoLayout kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt1_Head_Half_Closed_Eye_State_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kirby_metal_Head_Half_Closed_Switch_Option_Head_Half_Closed_mesh_layer_1_mat_override_Eyes__Kirby__Half__0),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kirby_metal_Head_Half_Closed_Switch_Option_Head_Half_Closed_mesh_layer_5_mat_override_Eyes__Kirby__Half__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt1_Head_Half_Closed_Eye_State_Switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kirby_metal_Head_Half_Closed_Switch_Option_Head_Half_Closed_mesh_layer_1_mat_override_Eyes__Kirby__Closed__1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kirby_metal_Head_Half_Closed_Switch_Option_Head_Half_Closed_mesh_layer_5_mat_override_Eyes__Kirby__Closed__1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt1_Head_Half_Closed_Eye_State_Switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kirby_metal_Head_Half_Closed_Switch_Option_Head_Half_Closed_mesh_layer_1_mat_override_Eyes__Kirby__Normal__2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kirby_metal_Head_Half_Closed_Switch_Option_Head_Half_Closed_mesh_layer_5_mat_override_Eyes__Kirby__Normal__2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt1_Head_Half_Closed_Eye_State_Switch_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kirby_metal_Head_Half_Closed_Switch_Option_Head_Half_Closed_mesh_layer_1_mat_override_Eyes__Kirby__Normal__2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kirby_metal_Head_Half_Closed_Switch_Option_Head_Half_Closed_mesh_layer_5_mat_override_Eyes__Kirby__Normal__2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt1_Head_Half_Closed_Eye_State_Switch_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kirby_metal_Head_Half_Closed_Switch_Option_Head_Half_Closed_mesh_layer_1_mat_override_Eyes__Kirby__Normal__2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kirby_metal_Head_Half_Closed_Switch_Option_Head_Half_Closed_mesh_layer_5_mat_override_Eyes__Kirby__Normal__2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt1_Head_Half_Closed_Eye_State_Switch_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kirby_metal_Head_Half_Closed_Switch_Option_Head_Half_Closed_mesh_layer_1_mat_override_Eyes__Kirby__Normal__2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kirby_metal_Head_Half_Closed_Switch_Option_Head_Half_Closed_mesh_layer_5_mat_override_Eyes__Kirby__Normal__2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt1_Head_Half_Closed_Eye_State_Switch_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kirby_metal_Head_Half_Closed_Switch_Option_Head_Half_Closed_mesh_layer_1_mat_override_Eyes__Kirby__Dead__3),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kirby_metal_Head_Half_Closed_Switch_Option_Head_Half_Closed_mesh_layer_5_mat_override_Eyes__Kirby__Dead__3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt1_Head_Half_Closed_Eye_State_Switch_opt8[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kirby_metal_Head_Half_Closed_Switch_Option_Head_Half_Closed_mesh_layer_1_mat_override_Eyes__Kirby__Shocked__4),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kirby_metal_Head_Half_Closed_Switch_Option_Head_Half_Closed_mesh_layer_5_mat_override_Eyes__Kirby__Shocked__4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt1_Head_Half_Closed_Eye_State_Switch_opt9[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kirby_metal_Head_Half_Closed_Switch_Option_Head_Half_Closed_mesh_layer_1_mat_override_Eyes__Kirby__Intense_Closed__5),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kirby_metal_Head_Half_Closed_Switch_Option_Head_Half_Closed_mesh_layer_5_mat_override_Eyes__Kirby__Intense_Closed__5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt1_Head_Half_Closed_Eye_State_Switch_opt10[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kirby_metal_Head_Half_Closed_Switch_Option_Head_Half_Closed_mesh_layer_1_mat_override_Eyes__Kirby__Angry__6),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kirby_metal_Head_Half_Closed_Switch_Option_Head_Half_Closed_mesh_layer_5_mat_override_Eyes__Kirby__Angry__6),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt1_Head_Half_Closed_Eye_State_Switch_opt11[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kirby_metal_Head_Half_Closed_Switch_Option_Head_Half_Closed_mesh_layer_1_mat_override_Eyes__Kirby__Angry__6),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kirby_metal_Head_Half_Closed_Switch_Option_Head_Half_Closed_mesh_layer_5_mat_override_Eyes__Kirby__Angry__6),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt1_Head_Half_Closed_Eye_State_Switch_opt12[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kirby_metal_Head_Half_Closed_Switch_Option_Head_Half_Closed_mesh_layer_1_mat_override_Eyes__Kirby__Normal__001_7),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kirby_metal_Head_Half_Closed_Switch_Option_Head_Half_Closed_mesh_layer_5_mat_override_Eyes__Kirby__Normal__001_7),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt1_Head_Half_Closed_Eye_State_Switch_opt13[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kirby_metal_Head_Half_Closed_Switch_Option_Head_Half_Closed_mesh_layer_1_mat_override_Eyes__Kirby__Half__001_8),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kirby_metal_Head_Half_Closed_Switch_Option_Head_Half_Closed_mesh_layer_5_mat_override_Eyes__Kirby__Half__001_8),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt1_Head_Half_Closed_Eye_State_Switch_opt14[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kirby_metal_Head_Half_Closed_Switch_Option_Head_Half_Closed_mesh_layer_1_mat_override_Eyes__Kirby__Closed__001_9),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kirby_metal_Head_Half_Closed_Switch_Option_Head_Half_Closed_mesh_layer_5_mat_override_Eyes__Kirby__Closed__001_9),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt1_Head_Half_Closed_Eye_State_Switch_opt15[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kirby_metal_Head_Half_Closed_Switch_Option_Head_Half_Closed_mesh_layer_1_mat_override_Eyes__Kirby__Normal__001_7),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kirby_metal_Head_Half_Closed_Switch_Option_Head_Half_Closed_mesh_layer_5_mat_override_Eyes__Kirby__Normal__001_7),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt1_Head_Half_Closed_Eye_State_Switch_opt16[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kirby_metal_Head_Half_Closed_Switch_Option_Head_Half_Closed_mesh_layer_1_mat_override_Eyes__Kirby__Normal__001_7),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kirby_metal_Head_Half_Closed_Switch_Option_Head_Half_Closed_mesh_layer_5_mat_override_Eyes__Kirby__Normal__001_7),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt1_Head_Half_Closed_Eye_State_Switch_opt17[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kirby_metal_Head_Half_Closed_Switch_Option_Head_Half_Closed_mesh_layer_1_mat_override_Eyes__Kirby__Normal__001_7),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kirby_metal_Head_Half_Closed_Switch_Option_Head_Half_Closed_mesh_layer_5_mat_override_Eyes__Kirby__Normal__001_7),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt1_Head_Half_Closed_Eye_State_Switch_opt18[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kirby_metal_Head_Half_Closed_Switch_Option_Head_Half_Closed_mesh_layer_1_mat_override_Eyes__Kirby__Normal__001_7),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kirby_metal_Head_Half_Closed_Switch_Option_Head_Half_Closed_mesh_layer_5_mat_override_Eyes__Kirby__Normal__001_7),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt1_Head_Half_Closed_Eye_State_Switch_opt19[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kirby_metal_Head_Half_Closed_Switch_Option_Head_Half_Closed_mesh_layer_1_mat_override_Eyes__Kirby__Dead__001_10),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kirby_metal_Head_Half_Closed_Switch_Option_Head_Half_Closed_mesh_layer_5_mat_override_Eyes__Kirby__Dead__001_10),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt1_Head_Half_Closed_Eye_State_Switch_opt20[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kirby_metal_Head_Half_Closed_Switch_Option_Head_Half_Closed_mesh_layer_1_mat_override_Eyes__Kirby__Shocked__001_11),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kirby_metal_Head_Half_Closed_Switch_Option_Head_Half_Closed_mesh_layer_5_mat_override_Eyes__Kirby__Shocked__001_11),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt1_Head_Half_Closed_Eye_State_Switch_opt21[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kirby_metal_Head_Half_Closed_Switch_Option_Head_Half_Closed_mesh_layer_1_mat_override_Eyes__Kirby__Intense_Closed__001_12),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kirby_metal_Head_Half_Closed_Switch_Option_Head_Half_Closed_mesh_layer_5_mat_override_Eyes__Kirby__Intense_Closed__001_12),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt1_Head_Half_Closed_Eye_State_Switch_opt22[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kirby_metal_Head_Half_Closed_Switch_Option_Head_Half_Closed_mesh_layer_1_mat_override_Eyes__Kirby__Angry__001_3),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kirby_metal_Head_Half_Closed_Switch_Option_Head_Half_Closed_mesh_layer_5_mat_override_Eyes__Kirby__Angry__001_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt1_Head_Half_Closed_Eye_State_Switch_opt23[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kirby_metal_Head_Half_Closed_Switch_Option_Head_Half_Closed_mesh_layer_1_mat_override_Eyes__Kirby__Angry__001_3),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kirby_metal_Head_Half_Closed_Switch_Option_Head_Half_Closed_mesh_layer_5_mat_override_Eyes__Kirby__Angry__001_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kirby_metal_Head_Inhaling[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, kirbyEyes_JJJ),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, kirby_metal_Head_Half_Closed_Switch_Option_Head_Half_Closed_mesh_layer_1),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kirby_metal_Head_Half_Closed_Switch_Option_Head_Half_Closed_mesh_layer_5),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt1_Head_Half_Closed_Eye_State_Switch_opt1),
			GEO_BRANCH(1, kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt1_Head_Half_Closed_Eye_State_Switch_opt2),
			GEO_BRANCH(1, kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt1_Head_Half_Closed_Eye_State_Switch_opt3),
			GEO_BRANCH(1, kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt1_Head_Half_Closed_Eye_State_Switch_opt4),
			GEO_BRANCH(1, kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt1_Head_Half_Closed_Eye_State_Switch_opt5),
			GEO_BRANCH(1, kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt1_Head_Half_Closed_Eye_State_Switch_opt6),
			GEO_BRANCH(1, kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt1_Head_Half_Closed_Eye_State_Switch_opt7),
			GEO_BRANCH(1, kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt1_Head_Half_Closed_Eye_State_Switch_opt8),
			GEO_BRANCH(1, kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt1_Head_Half_Closed_Eye_State_Switch_opt9),
			GEO_BRANCH(1, kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt1_Head_Half_Closed_Eye_State_Switch_opt10),
			GEO_BRANCH(1, kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt1_Head_Half_Closed_Eye_State_Switch_opt11),
			GEO_BRANCH(1, kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt1_Head_Half_Closed_Eye_State_Switch_opt12),
			GEO_BRANCH(1, kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt1_Head_Half_Closed_Eye_State_Switch_opt13),
			GEO_BRANCH(1, kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt1_Head_Half_Closed_Eye_State_Switch_opt14),
			GEO_BRANCH(1, kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt1_Head_Half_Closed_Eye_State_Switch_opt15),
			GEO_BRANCH(1, kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt1_Head_Half_Closed_Eye_State_Switch_opt16),
			GEO_BRANCH(1, kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt1_Head_Half_Closed_Eye_State_Switch_opt17),
			GEO_BRANCH(1, kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt1_Head_Half_Closed_Eye_State_Switch_opt18),
			GEO_BRANCH(1, kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt1_Head_Half_Closed_Eye_State_Switch_opt19),
			GEO_BRANCH(1, kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt1_Head_Half_Closed_Eye_State_Switch_opt20),
			GEO_BRANCH(1, kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt1_Head_Half_Closed_Eye_State_Switch_opt21),
			GEO_BRANCH(1, kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt1_Head_Half_Closed_Eye_State_Switch_opt22),
			GEO_BRANCH(1, kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt1_Head_Half_Closed_Eye_State_Switch_opt23),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt2_Head_Closed_Eye_State_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kirby_metal_Head_Closed_Switch_Option_Head_Closed_mesh_layer_1_mat_override_Eyes__Kirby__Normal__0),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kirby_metal_Head_Closed_Switch_Option_Head_Closed_mesh_layer_5_mat_override_Eyes__Kirby__Normal__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt2_Head_Closed_Eye_State_Switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kirby_metal_Head_Closed_Switch_Option_Head_Closed_mesh_layer_1_mat_override_Eyes__Kirby__Normal__0),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kirby_metal_Head_Closed_Switch_Option_Head_Closed_mesh_layer_5_mat_override_Eyes__Kirby__Normal__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt2_Head_Closed_Eye_State_Switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kirby_metal_Head_Closed_Switch_Option_Head_Closed_mesh_layer_1_mat_override_Eyes__Kirby__Normal__0),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kirby_metal_Head_Closed_Switch_Option_Head_Closed_mesh_layer_5_mat_override_Eyes__Kirby__Normal__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt2_Head_Closed_Eye_State_Switch_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kirby_metal_Head_Closed_Switch_Option_Head_Closed_mesh_layer_1_mat_override_Eyes__Kirby__Normal__0),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kirby_metal_Head_Closed_Switch_Option_Head_Closed_mesh_layer_5_mat_override_Eyes__Kirby__Normal__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt2_Head_Closed_Eye_State_Switch_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kirby_metal_Head_Closed_Switch_Option_Head_Closed_mesh_layer_1_mat_override_Eyes__Kirby__Normal__0),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kirby_metal_Head_Closed_Switch_Option_Head_Closed_mesh_layer_5_mat_override_Eyes__Kirby__Normal__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt2_Head_Closed_Eye_State_Switch_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kirby_metal_Head_Closed_Switch_Option_Head_Closed_mesh_layer_1_mat_override_Eyes__Kirby__Normal__0),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kirby_metal_Head_Closed_Switch_Option_Head_Closed_mesh_layer_5_mat_override_Eyes__Kirby__Normal__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt2_Head_Closed_Eye_State_Switch_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kirby_metal_Head_Closed_Switch_Option_Head_Closed_mesh_layer_1_mat_override_Eyes__Kirby__Intense_Closed__1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kirby_metal_Head_Closed_Switch_Option_Head_Closed_mesh_layer_5_mat_override_Eyes__Kirby__Intense_Closed__1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt2_Head_Closed_Eye_State_Switch_opt8[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kirby_metal_Head_Closed_Switch_Option_Head_Closed_mesh_layer_1_mat_override_Eyes__Kirby__Intense_Closed__1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kirby_metal_Head_Closed_Switch_Option_Head_Closed_mesh_layer_5_mat_override_Eyes__Kirby__Intense_Closed__1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt2_Head_Closed_Eye_State_Switch_opt9[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kirby_metal_Head_Closed_Switch_Option_Head_Closed_mesh_layer_1_mat_override_Eyes__Kirby__Intense_Closed__1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kirby_metal_Head_Closed_Switch_Option_Head_Closed_mesh_layer_5_mat_override_Eyes__Kirby__Intense_Closed__1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt2_Head_Closed_Eye_State_Switch_opt10[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kirby_metal_Head_Closed_Switch_Option_Head_Closed_mesh_layer_1_mat_override_Eyes__Kirby__Angry__2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kirby_metal_Head_Closed_Switch_Option_Head_Closed_mesh_layer_5_mat_override_Eyes__Kirby__Angry__2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt2_Head_Closed_Eye_State_Switch_opt11[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kirby_metal_Head_Closed_Switch_Option_Head_Closed_mesh_layer_1_mat_override_Eyes__Kirby__Angry__2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kirby_metal_Head_Closed_Switch_Option_Head_Closed_mesh_layer_5_mat_override_Eyes__Kirby__Angry__2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt2_Head_Closed_Eye_State_Switch_opt12[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kirby_metal_Head_Closed_Switch_Option_Head_Closed_mesh_layer_1_mat_override_Eyes__Kirby__Normal__001_3),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kirby_metal_Head_Closed_Switch_Option_Head_Closed_mesh_layer_5_mat_override_Eyes__Kirby__Normal__001_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt2_Head_Closed_Eye_State_Switch_opt13[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kirby_metal_Head_Closed_Switch_Option_Head_Closed_mesh_layer_1_mat_override_Eyes__Kirby__Half__001_4),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kirby_metal_Head_Closed_Switch_Option_Head_Closed_mesh_layer_5_mat_override_Eyes__Kirby__Half__001_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt2_Head_Closed_Eye_State_Switch_opt14[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kirby_metal_Head_Closed_Switch_Option_Head_Closed_mesh_layer_1_mat_override_Eyes__Kirby__Closed__001_5),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kirby_metal_Head_Closed_Switch_Option_Head_Closed_mesh_layer_5_mat_override_Eyes__Kirby__Closed__001_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt2_Head_Closed_Eye_State_Switch_opt15[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kirby_metal_Head_Closed_Switch_Option_Head_Closed_mesh_layer_1_mat_override_Eyes__Kirby__Normal__001_3),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kirby_metal_Head_Closed_Switch_Option_Head_Closed_mesh_layer_5_mat_override_Eyes__Kirby__Normal__001_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt2_Head_Closed_Eye_State_Switch_opt16[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kirby_metal_Head_Closed_Switch_Option_Head_Closed_mesh_layer_1_mat_override_Eyes__Kirby__Normal__001_3),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kirby_metal_Head_Closed_Switch_Option_Head_Closed_mesh_layer_5_mat_override_Eyes__Kirby__Normal__001_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt2_Head_Closed_Eye_State_Switch_opt17[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kirby_metal_Head_Closed_Switch_Option_Head_Closed_mesh_layer_1_mat_override_Eyes__Kirby__Normal__001_3),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kirby_metal_Head_Closed_Switch_Option_Head_Closed_mesh_layer_5_mat_override_Eyes__Kirby__Normal__001_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt2_Head_Closed_Eye_State_Switch_opt18[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kirby_metal_Head_Closed_Switch_Option_Head_Closed_mesh_layer_1_mat_override_Eyes__Kirby__Normal__001_3),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kirby_metal_Head_Closed_Switch_Option_Head_Closed_mesh_layer_5_mat_override_Eyes__Kirby__Normal__001_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt2_Head_Closed_Eye_State_Switch_opt19[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kirby_metal_Head_Closed_Switch_Option_Head_Closed_mesh_layer_1_mat_override_Eyes__Kirby__Intense_Closed__001_6),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kirby_metal_Head_Closed_Switch_Option_Head_Closed_mesh_layer_5_mat_override_Eyes__Kirby__Intense_Closed__001_6),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt2_Head_Closed_Eye_State_Switch_opt20[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kirby_metal_Head_Closed_Switch_Option_Head_Closed_mesh_layer_1_mat_override_Eyes__Kirby__Intense_Closed__001_6),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kirby_metal_Head_Closed_Switch_Option_Head_Closed_mesh_layer_5_mat_override_Eyes__Kirby__Intense_Closed__001_6),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt2_Head_Closed_Eye_State_Switch_opt21[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kirby_metal_Head_Closed_Switch_Option_Head_Closed_mesh_layer_1_mat_override_Eyes__Kirby__Intense_Closed__001_6),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kirby_metal_Head_Closed_Switch_Option_Head_Closed_mesh_layer_5_mat_override_Eyes__Kirby__Intense_Closed__001_6),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt2_Head_Closed_Eye_State_Switch_opt22[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kirby_metal_Head_Closed_Switch_Option_Head_Closed_mesh_layer_1_mat_override_Eyes__Kirby__Angry__001_7),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kirby_metal_Head_Closed_Switch_Option_Head_Closed_mesh_layer_5_mat_override_Eyes__Kirby__Angry__001_7),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt2_Head_Closed_Eye_State_Switch_opt23[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kirby_metal_Head_Closed_Switch_Option_Head_Closed_mesh_layer_1_mat_override_Eyes__Kirby__Angry__001_7),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kirby_metal_Head_Closed_Switch_Option_Head_Closed_mesh_layer_5_mat_override_Eyes__Kirby__Angry__001_7),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kirby_metal_Head_Full[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, kirbyEyes_JJJ),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, kirby_metal_Head_Closed_Switch_Option_Head_Closed_mesh_layer_1),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kirby_metal_Head_Closed_Switch_Option_Head_Closed_mesh_layer_5),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt2_Head_Closed_Eye_State_Switch_opt1),
			GEO_BRANCH(1, kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt2_Head_Closed_Eye_State_Switch_opt2),
			GEO_BRANCH(1, kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt2_Head_Closed_Eye_State_Switch_opt3),
			GEO_BRANCH(1, kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt2_Head_Closed_Eye_State_Switch_opt4),
			GEO_BRANCH(1, kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt2_Head_Closed_Eye_State_Switch_opt5),
			GEO_BRANCH(1, kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt2_Head_Closed_Eye_State_Switch_opt6),
			GEO_BRANCH(1, kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt2_Head_Closed_Eye_State_Switch_opt7),
			GEO_BRANCH(1, kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt2_Head_Closed_Eye_State_Switch_opt8),
			GEO_BRANCH(1, kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt2_Head_Closed_Eye_State_Switch_opt9),
			GEO_BRANCH(1, kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt2_Head_Closed_Eye_State_Switch_opt10),
			GEO_BRANCH(1, kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt2_Head_Closed_Eye_State_Switch_opt11),
			GEO_BRANCH(1, kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt2_Head_Closed_Eye_State_Switch_opt12),
			GEO_BRANCH(1, kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt2_Head_Closed_Eye_State_Switch_opt13),
			GEO_BRANCH(1, kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt2_Head_Closed_Eye_State_Switch_opt14),
			GEO_BRANCH(1, kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt2_Head_Closed_Eye_State_Switch_opt15),
			GEO_BRANCH(1, kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt2_Head_Closed_Eye_State_Switch_opt16),
			GEO_BRANCH(1, kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt2_Head_Closed_Eye_State_Switch_opt17),
			GEO_BRANCH(1, kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt2_Head_Closed_Eye_State_Switch_opt18),
			GEO_BRANCH(1, kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt2_Head_Closed_Eye_State_Switch_opt19),
			GEO_BRANCH(1, kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt2_Head_Closed_Eye_State_Switch_opt20),
			GEO_BRANCH(1, kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt2_Head_Closed_Eye_State_Switch_opt21),
			GEO_BRANCH(1, kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt2_Head_Closed_Eye_State_Switch_opt22),
			GEO_BRANCH(1, kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt2_Head_Closed_Eye_State_Switch_opt23),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kirby_metal_Classic_Kirby_Arm_Left[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, kirby_metal_Classic_Arm_Switch_Option_Classic_Arm_Left_Color_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 136, 0, 0, NULL),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kirby_metal_Classic_Kirby_Arm_Right[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, kirby_metal_Classic_Arm_Switch_Option_Classic_Arm__RightColor_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 136, 0, 0, NULL),
			GEO_CLOSE_NODE(),
			GEO_HELD_OBJECT(0, 136, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt0_Eye_State_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kirby_metal_Head_DL_mesh_layer_1_mat_override_Eyes__Kirby__Half__0),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kirby_metal_Head_DL_mesh_layer_5_mat_override_Eyes__Kirby__Half__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt0_Eye_State_Switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kirby_metal_Head_DL_mesh_layer_1_mat_override_Eyes__Kirby__Closed__1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kirby_metal_Head_DL_mesh_layer_5_mat_override_Eyes__Kirby__Closed__1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt0_Eye_State_Switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kirby_metal_Head_DL_mesh_layer_1_mat_override_Eyes__Kirby__Normal__2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kirby_metal_Head_DL_mesh_layer_5_mat_override_Eyes__Kirby__Normal__2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt0_Eye_State_Switch_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kirby_metal_Head_DL_mesh_layer_1_mat_override_Eyes__Kirby__Normal__2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kirby_metal_Head_DL_mesh_layer_5_mat_override_Eyes__Kirby__Normal__2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt0_Eye_State_Switch_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kirby_metal_Head_DL_mesh_layer_1_mat_override_Eyes__Kirby__Normal__2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kirby_metal_Head_DL_mesh_layer_5_mat_override_Eyes__Kirby__Normal__2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt0_Eye_State_Switch_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kirby_metal_Head_DL_mesh_layer_1_mat_override_Eyes__Kirby__Normal__2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kirby_metal_Head_DL_mesh_layer_5_mat_override_Eyes__Kirby__Normal__2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt0_Eye_State_Switch_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kirby_metal_Head_DL_mesh_layer_1_mat_override_Eyes__Kirby__Dead__3),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kirby_metal_Head_DL_mesh_layer_5_mat_override_Eyes__Kirby__Dead__3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt0_Eye_State_Switch_opt8[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kirby_metal_Head_DL_mesh_layer_1_mat_override_Eyes__Kirby__Shocked__4),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kirby_metal_Head_DL_mesh_layer_5_mat_override_Eyes__Kirby__Shocked__4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt0_Eye_State_Switch_opt9[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kirby_metal_Head_DL_mesh_layer_1_mat_override_Eyes__Kirby__Intense_Closed__5),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kirby_metal_Head_DL_mesh_layer_5_mat_override_Eyes__Kirby__Intense_Closed__5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt0_Eye_State_Switch_opt10[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kirby_metal_Head_DL_mesh_layer_1_mat_override_Eyes__Kirby__Angry__6),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kirby_metal_Head_DL_mesh_layer_5_mat_override_Eyes__Kirby__Angry__6),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt0_Eye_State_Switch_opt11[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kirby_metal_Head_DL_mesh_layer_1_mat_override_Eyes__Kirby__Evil__7),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kirby_metal_Head_DL_mesh_layer_5_mat_override_Eyes__Kirby__Evil__7),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt0_Eye_State_Switch_opt12[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kirby_metal_Head_DL_mesh_layer_1_mat_override_Eyes__Kirby__Normal__001_8),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kirby_metal_Head_DL_mesh_layer_5_mat_override_Eyes__Kirby__Normal__001_8),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt0_Eye_State_Switch_opt13[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kirby_metal_Head_DL_mesh_layer_1_mat_override_Eyes__Kirby__Half__001_9),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kirby_metal_Head_DL_mesh_layer_5_mat_override_Eyes__Kirby__Half__001_9),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt0_Eye_State_Switch_opt14[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kirby_metal_Head_DL_mesh_layer_1_mat_override_Eyes__Kirby__Closed__001_10),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kirby_metal_Head_DL_mesh_layer_5_mat_override_Eyes__Kirby__Closed__001_10),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt0_Eye_State_Switch_opt15[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kirby_metal_Head_DL_mesh_layer_1_mat_override_Eyes__Kirby__Normal__001_8),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kirby_metal_Head_DL_mesh_layer_5_mat_override_Eyes__Kirby__Normal__001_8),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt0_Eye_State_Switch_opt16[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kirby_metal_Head_DL_mesh_layer_1_mat_override_Eyes__Kirby__Normal__001_8),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kirby_metal_Head_DL_mesh_layer_5_mat_override_Eyes__Kirby__Normal__001_8),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt0_Eye_State_Switch_opt17[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kirby_metal_Head_DL_mesh_layer_1_mat_override_Eyes__Kirby__Normal__001_8),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kirby_metal_Head_DL_mesh_layer_5_mat_override_Eyes__Kirby__Normal__001_8),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt0_Eye_State_Switch_opt18[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kirby_metal_Head_DL_mesh_layer_1_mat_override_Eyes__Kirby__Normal__001_8),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kirby_metal_Head_DL_mesh_layer_5_mat_override_Eyes__Kirby__Normal__001_8),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt0_Eye_State_Switch_opt19[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kirby_metal_Head_DL_mesh_layer_1_mat_override_Eyes__Kirby__Dead__001_11),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kirby_metal_Head_DL_mesh_layer_5_mat_override_Eyes__Kirby__Dead__001_11),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt0_Eye_State_Switch_opt20[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kirby_metal_Head_DL_mesh_layer_1_mat_override_Eyes__Kirby__Shocked__001_12),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kirby_metal_Head_DL_mesh_layer_5_mat_override_Eyes__Kirby__Shocked__001_12),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt0_Eye_State_Switch_opt21[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kirby_metal_Head_DL_mesh_layer_1_mat_override_Eyes__Kirby__Intense_Closed__001_13),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kirby_metal_Head_DL_mesh_layer_5_mat_override_Eyes__Kirby__Intense_Closed__001_13),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt0_Eye_State_Switch_opt22[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kirby_metal_Head_DL_mesh_layer_1_mat_override_Eyes__Kirby__Angry__001_14),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kirby_metal_Head_DL_mesh_layer_5_mat_override_Eyes__Kirby__Angry__001_14),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt0_Eye_State_Switch_opt23[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kirby_metal_Head_DL_mesh_layer_1_mat_override_Eyes__Kirby__Evil__001_15),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kirby_metal_Head_DL_mesh_layer_5_mat_override_Eyes__Kirby__Evil__001_15),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt0_Mouth_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kirby_metal_Mouth_DL_mesh_layer_5_mat_override_Mouth__Kirby__Happy__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt0_Mouth_Switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kirby_metal_Mouth_DL_mesh_layer_5_mat_override_Mouth__Kirby__Smile__1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt0_Mouth_Switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kirby_metal_Mouth_DL_mesh_layer_5_mat_override_Mouth__Kirby__Frown__2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt0_Mouth_Switch_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kirby_metal_Mouth_DL_mesh_layer_5_mat_override_Mouth__Kirby__Open__3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt0_Mouth_Switch_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kirby_metal_Mouth_DL_mesh_layer_5_mat_override_Mouth__Kirby__Evil__4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt0_Mouth_Switch_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kirby_metal_Mouth_DL_mesh_layer_5_mat_override_Mouth__Kirby__Smile__001_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt0_Mouth_Switch_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kirby_metal_Mouth_DL_mesh_layer_5_mat_override_Mouth__Kirby__Frown__001_6),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kirby_metal_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(1, 180, 100),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 22910),
			GEO_OPEN_NODE(),
				GEO_ASM(LAYER_OPAQUE + 3, geo_mario_set_player_colors),
				GEO_ASM(LAYER_ALPHA + 3, geo_mario_set_player_colors),
				GEO_ASM(LAYER_TRANSPARENT + 3, geo_mario_set_player_colors),
				GEO_ASM(LAYER_OPAQUE << 2, geo_mirror_mario_backface_culling),
				GEO_ASM(LAYER_ALPHA << 2, geo_mirror_mario_backface_culling),
				GEO_ASM(LAYER_TRANSPARENT << 2, geo_mirror_mario_backface_culling),
				GEO_ASM(0, geo_mirror_mario_set_alpha),
				GEO_SWITCH_CASE(0, geo_switch_mario_stand_run),
				GEO_OPEN_NODE(),
					GEO_NODE_START(),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_SCALE(LAYER_OPAQUE, 46867),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_move_mario_part_from_parent),
									GEO_ASM(0, geo_mario_tilt_torso),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(0, geo_mario_head_rotation),
												GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
												GEO_OPEN_NODE(),
													GEO_SWITCH_CASE(0, kirbyInhale_JJJ),
													GEO_OPEN_NODE(),
														GEO_NODE_START(),
														GEO_OPEN_NODE(),
															GEO_SWITCH_CASE(0, kirbyEyes_JJJ),
															GEO_OPEN_NODE(),
																GEO_NODE_START(),
																GEO_OPEN_NODE(),
																	GEO_DISPLAY_LIST(LAYER_OPAQUE, kirby_metal_Head_DL_mesh_layer_1),
																	GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kirby_metal_Head_DL_mesh_layer_5),
																GEO_CLOSE_NODE(),
																GEO_BRANCH(1, kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt0_Eye_State_Switch_opt1),
																GEO_BRANCH(1, kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt0_Eye_State_Switch_opt2),
																GEO_BRANCH(1, kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt0_Eye_State_Switch_opt3),
																GEO_BRANCH(1, kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt0_Eye_State_Switch_opt4),
																GEO_BRANCH(1, kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt0_Eye_State_Switch_opt5),
																GEO_BRANCH(1, kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt0_Eye_State_Switch_opt6),
																GEO_BRANCH(1, kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt0_Eye_State_Switch_opt7),
																GEO_BRANCH(1, kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt0_Eye_State_Switch_opt8),
																GEO_BRANCH(1, kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt0_Eye_State_Switch_opt9),
																GEO_BRANCH(1, kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt0_Eye_State_Switch_opt10),
																GEO_BRANCH(1, kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt0_Eye_State_Switch_opt11),
																GEO_BRANCH(1, kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt0_Eye_State_Switch_opt12),
																GEO_BRANCH(1, kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt0_Eye_State_Switch_opt13),
																GEO_BRANCH(1, kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt0_Eye_State_Switch_opt14),
																GEO_BRANCH(1, kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt0_Eye_State_Switch_opt15),
																GEO_BRANCH(1, kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt0_Eye_State_Switch_opt16),
																GEO_BRANCH(1, kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt0_Eye_State_Switch_opt17),
																GEO_BRANCH(1, kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt0_Eye_State_Switch_opt18),
																GEO_BRANCH(1, kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt0_Eye_State_Switch_opt19),
																GEO_BRANCH(1, kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt0_Eye_State_Switch_opt20),
																GEO_BRANCH(1, kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt0_Eye_State_Switch_opt21),
																GEO_BRANCH(1, kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt0_Eye_State_Switch_opt22),
																GEO_BRANCH(1, kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt0_Eye_State_Switch_opt23),
															GEO_CLOSE_NODE(),
															GEO_SWITCH_CASE(0, kirbyMouth_JJJ),
															GEO_OPEN_NODE(),
																GEO_NODE_START(),
																GEO_OPEN_NODE(),
																	GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kirby_metal_Mouth_DL_mesh_layer_5),
																GEO_CLOSE_NODE(),
																GEO_BRANCH(1, kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt0_Mouth_Switch_opt1),
																GEO_BRANCH(1, kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt0_Mouth_Switch_opt2),
																GEO_BRANCH(1, kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt0_Mouth_Switch_opt3),
																GEO_BRANCH(1, kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt0_Mouth_Switch_opt4),
																GEO_BRANCH(1, kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt0_Mouth_Switch_opt5),
																GEO_BRANCH(1, kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt0_Mouth_Switch_opt6),
																GEO_BRANCH(1, kirby_metal_7_LoD_Switch__Unused__opt0_Inhale_State_Switch_opt0_Mouth_Switch_opt7),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
														GEO_BRANCH(1, kirby_metal_Head_Inhaling),
														GEO_BRANCH(1, kirby_metal_Head_Full),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, -2, 0, 144, NULL),
											GEO_OPEN_NODE(),
												GEO_SWITCH_CASE(0, kirbyClassic_JJJ),
												GEO_OPEN_NODE(),
													GEO_NODE_START(),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, kirby_metal_Left_Arm_Color_mesh_layer_1),
														GEO_OPEN_NODE(),
															GEO_ANIMATED_PART(LAYER_OPAQUE, 136, -1, 0, NULL),
															GEO_OPEN_NODE(),
																GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
													GEO_BRANCH(1, kirby_metal_Classic_Kirby_Arm_Left),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, -1, 0, -144, NULL),
											GEO_OPEN_NODE(),
												GEO_SWITCH_CASE(0, kirbyClassic_JJJ),
												GEO_OPEN_NODE(),
													GEO_NODE_START(),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, kirby_metal_Right_Arm_Color_mesh_layer_1),
														GEO_OPEN_NODE(),
															GEO_ANIMATED_PART(LAYER_OPAQUE, 126, 0, 0, NULL),
															GEO_OPEN_NODE(),
																GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
															GEO_CLOSE_NODE(),
															GEO_HELD_OBJECT(0, 126, 0, 0, geo_switch_mario_hand_grab_pos),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
													GEO_BRANCH(1, kirby_metal_Classic_Kirby_Arm_Right),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, -94, -8, 106, NULL),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 27, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 22, 0, 0, 0, 0, 1),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, kirby_metal_Left_Shoe_mesh_layer_1),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, -94, -8, -106, NULL),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 27, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 22, 0, 0, 0, 0, 1),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_SCALE(LAYER_OPAQUE, 65536),
														GEO_SCALE(LAYER_FORCE, 65536),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(LAYER_OPAQUE, kirby_metal_Right_Shoe_DL_mesh_layer_1),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ASM((LAYER_OPAQUE << 2) | 1, geo_mirror_mario_backface_culling),
				GEO_ASM((LAYER_ALPHA << 2) | 1, geo_mirror_mario_backface_culling),
				GEO_ASM((LAYER_TRANSPARENT << 2) | 1, geo_mirror_mario_backface_culling),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kirby_metal_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, kirby_metal_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
